# Generated by Django 6.0.6 on 2026-07-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_absence_leaverequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvée', 'Approuvée'), ('Refusée', 'Refusée'), ('Remboursée', 'Remboursée')], default='En attente', max_length=20)),
                ('repayment_date', models.DateField(blank=True, null=True)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_advances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]