# Generated by Django 6.0.6 on 2026-08-14 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rolepermission'),
        ('hr', '0007_employee_leave_credit_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, help_text='The role this employee has for permissions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.rolepermission'),
        ),
    ]
