# Generated by Django 6.0.6 on 2026-07-15 18:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_payment'),
        ('crm', '0006_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNAMClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnam_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Approuvée', 'Approuvée'), ('Rejetée', 'Rejetée'), ('Remboursée', 'Remboursée')], default='En attente', max_length=20)),
                ('amount_claimed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_reimbursed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnam_claims', to='accounting.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnam_claims', to='crm.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]