# Generated by Django 6.0.6 on 2026-08-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoicelineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('salary_advance', 'Avance sur salaire'), ('supplier', 'Fournisseur'), ('other', 'Autre')], default='other', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque')], default='bank_transfer', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
