# Generated by Django 6.0.6 on 2026-08-12 13:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_dunning_action'),
        ('crm', '0015_machine_calibration_interval_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dunningaction',
            options={'ordering': ['-action_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='dunningaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Frais d'escalade appliqués (5% du solde dû au passage huissier)", max_digits=10),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='accounting__status_24bfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', 'status'], name='accounting__patient_264cd8_idx'),
        ),
    ]
