# Generated by Django 4.2.30 on 2026-08-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_invoice_cnam_split'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='accounting_invoice_apci_idx',
        ),
    ]
