from django.test import TestCase
from rest_framework.test import APIClient
from rest_framework import status
# Create your tests here.
from .models import Appointment, Complaint, Machine, Patient, Room, Ticket, TreatmentPlan, TreatmentSession
from django.contrib.auth.models import User
from django.contrib.auth.models import User
class PatientModelTestCase(TestCase):
    def setUp(self):
        self.client=APIClient()
        self.user = User.objects.create_user(
            username="tester",
            password="testpass123",
        )
        self.client.force_authenticate(user=self.user)
        self.patient_data={
            "first_name": "Ali",
            "last_name": "Mansouri",
            "cin": "12345678",
            "phone": "22123456",
            "email": "ali@example.com",
            "birth_date": "1995-04-10",
            "address": "Tunis",
            "medical_record_number": "MR-0001",
            "diagnosis": "Test diagnosis",
            "notes": "First test patient",
        }
        
    def test_create_patient(self):
        response = self.client.post("/api/crm/patients/", self.patient_data, format="json")

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(Patient.objects.count(), 1)
        # MRN is auto-generated by the backend — just verify it was set
        mrn = Patient.objects.first().medical_record_number
        self.assertTrue(mrn.startswith("MRN-"), f"Unexpected MRN format: {mrn}")

    def test_list_patients(self):
        Patient.objects.create(**self.patient_data)

        response = self.client.get("/api/crm/patients/")

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["count"], 1)
        
class AppointmentApiTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = User.objects.create_user(
            username="tester",
            password="testpass123",
        )
        self.client.force_authenticate(user=self.user)
        self.patient = Patient.objects.create(
            first_name="Ali",
            last_name="Mansouri",
            cin="12345678",
            phone="22123456",
            email="ali@example.com",
            birth_date="1995-04-10",
            address="Tunis",
            medical_record_number="MR-0001",
            diagnosis="Test diagnosis",
            notes="First test patient",
        )

    def test_create_appointment(self):
        data = {
            "patient": self.patient.id,
            "title": "Consultation initiale",
            "appointment_date": "2026-07-10T09:00:00Z",
            "status": "scheduled",
            "reason": "First consultation",
            "notes": "Bring medical files",
        }

        response = self.client.post("/api/crm/appointments/", data, format="json")

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data["title"], "Consultation initiale")
        self.assertEqual(response.data["patient"], self.patient.id)

    def test_list_appointments(self):
        self.patient.appointments.create(
            title="Consultation initiale",
            appointment_date="2026-07-10T09:00:00Z",
            status="scheduled",
            reason="First consultation",
            notes="Bring medical files",
        )

        response = self.client.get("/api/crm/appointments/")

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["count"], 1)

class TreatmentPlanApiTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = User.objects.create_user(
            username="tester",
            password="testpass123",
        )
        self.client.force_authenticate(user=self.user)
        self.patient = Patient.objects.create(
            first_name="Ali",
            last_name="Mansouri",
            cin="12345678",
            phone="22123456",
            email="ali@example.com",
            birth_date="1995-04-10",
            address="Tunis",
            medical_record_number="MR-0001",
            diagnosis="Test diagnosis",
            notes="First test patient",
        )

    def test_create_treatment_plan(self):
        data = {
            "patient": self.patient.id,
            "name": "Radiotherapy Plan A",
            "diagnosis": "Lung cancer",
            "protocol": "Standard fractionated radiotherapy",
            "total_sessions": 30,
            "dose_per_session": "2.00",
            "total_dose": "60.00",
            "start_date": "2026-07-15",
            "end_date": "2026-08-30",
            "status": "active",
            "notes": "Initial treatment plan",
        }

        response = self.client.post("/api/crm/treatment-plans/", data, format="json")

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data["name"], "Radiotherapy Plan A")
        self.assertEqual(response.data["patient"], self.patient.id)

    def test_list_treatment_plans(self):
        TreatmentPlan.objects.create(
            patient=self.patient,
            name="Radiotherapy Plan A",
            diagnosis="Lung cancer",
            protocol="Standard fractionated radiotherapy",
            total_sessions=30,
            dose_per_session="2.00",
            total_dose="60.00",
            start_date="2026-07-15",
            end_date="2026-08-30",
            status="active",
            notes="Initial treatment plan",
        )

        response = self.client.get("/api/crm/treatment-plans/")

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["count"], 1)
    
class TreatmentSessionApiTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = User.objects.create_user(
            username="tester",
            password="testpass123",
        )
        self.client.force_authenticate(user=self.user)
        self.patient = Patient.objects.create(
            first_name="Ali",
            last_name="Mansouri",
            cin="12345678",
            phone="22123456",
            email="ali@example.com",
            birth_date="1995-04-10",
            address="Tunis",
            medical_record_number="MR-0001",
            diagnosis="Test diagnosis",
            notes="First test patient",
        )
        self.treatment_plan = TreatmentPlan.objects.create(
            patient=self.patient,
            name="Radiotherapy Plan A",
            diagnosis="Lung cancer",
            protocol="Standard fractionated radiotherapy",
            total_sessions=30,
            dose_per_session="2.00",
            total_dose="60.00",
            start_date="2026-07-15",
            end_date="2026-08-30",
            status="active",
            notes="Initial treatment plan",
        )

    def setUp(self):
        self.client = APIClient()
        self.user = User.objects.create_user(
            username="tester",
            password="testpass123",
        )
        self.client.force_authenticate(user=self.user)
        self.patient = Patient.objects.create(
            first_name="Ali",
            last_name="Mansouri",
            cin="12345678",
            phone="22123456",
            email="ali@example.com",
            birth_date="1995-04-10",
            address="Tunis",
            medical_record_number="MR-0001",
            diagnosis="Test diagnosis",
            notes="First test patient",
        )
        self.treatment_plan = TreatmentPlan.objects.create(
            patient=self.patient,
            name="Radiotherapy Plan A",
            diagnosis="Lung cancer",
            protocol="Standard fractionated radiotherapy",
            total_sessions=30,
            dose_per_session="2.00",
            total_dose="60.00",
            start_date="2026-07-15",
            end_date="2026-08-30",
            status="active",
            notes="Initial treatment plan",
        )
        self.machine = Machine.objects.create(name="LINAC 1", status="active")
        self.room = Room.objects.create(name="Room A", status="active")

    def test_create_treatment_session(self):
        data = {
            "patient": self.patient.id,
            "treatment_plan": self.treatment_plan.id,
            "session_number": 1,
            "scheduled_datetime": "2026-07-16T09:00:00Z",
            "actual_datetime": None,
            "status": "scheduled",
            "machine": self.machine.id,
            "room": self.room.id,
            "dose_delivered": "2.00",
            "notes": "First session",
        }

        response = self.client.post("/api/crm/treatment-sessions/", data, format="json")

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data["session_number"], 1)
        self.assertEqual(response.data["patient"], self.patient.id)
        self.assertEqual(response.data["treatment_plan"], self.treatment_plan.id)
        self.assertEqual(response.data["machine"], self.machine.id)
        self.assertEqual(response.data["machine_name"], "LINAC 1")
        
    def test_list_treatment_sessions(self):
            TreatmentSession.objects.create(
                patient=self.patient,
                treatment_plan=self.treatment_plan,
                session_number=1,
                scheduled_datetime="2026-07-16T09:00:00Z",
                status="scheduled",
                machine=self.machine,
                room=self.room,
                dose_delivered="2.00",
                notes="First session",
            )

            response = self.client.get("/api/crm/treatment-sessions/")

            self.assertEqual(response.status_code, status.HTTP_200_OK)
            self.assertEqual(response.data["count"], 1)

class CrmFilterSearchTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = User.objects.create_user(
            username="crm_reader",
            password="testpass123",
        )
        self.client.force_authenticate(user=self.user)
        self.patient_ali = Patient.objects.create(
            first_name="Ali",
            last_name="Mansouri",
            cin="12345678",
            phone="22123456",
            email="ali@example.com",
            birth_date="1995-04-10",
            address="Tunis",
            medical_record_number="MR-0001",
            diagnosis="Test diagnosis",
            notes="First test patient",
        )
        self.patient_sara = Patient.objects.create(
            first_name="Sara",
            last_name="Ben Ali",
            cin="87654321",
            phone="22999999",
            email="sara@example.com",
            birth_date="1990-01-20",
            address="Sousse",
            medical_record_number="MR-0002",
            diagnosis="Second diagnosis",
            notes="Second test patient",
        )
        self.plan = TreatmentPlan.objects.create(
            patient=self.patient_ali,
            name="Radiotherapy Plan A",
            total_sessions=30,
            dose_per_session="2.00",
            total_dose="60.00",
            status="active",
        )

    def test_search_patients(self):
        response = self.client.get("/api/crm/patients/?search=Mansouri")

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["count"], 1)
        self.assertEqual(response.data["results"][0]["first_name"], "Ali")

    def test_filter_treatment_plans_by_status(self):
        response = self.client.get("/api/crm/treatment-plans/?status=active")

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["count"], 1)
        self.assertEqual(response.data["results"][0]["status"], "active")

    def test_filter_treatment_sessions_by_status(self):
        TreatmentSession.objects.create(
            patient=self.patient_ali,
            treatment_plan=self.plan,
            session_number=1,
            scheduled_datetime="2026-07-16T09:00:00Z",
            status="completed",
            dose_delivered="2.00",
        )

        response = self.client.get("/api/crm/treatment-sessions/?status=completed")

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["count"], 1)
        self.assertEqual(response.data["results"][0]["status"], "completed")
        
class CrmPermissionTests(TestCase):
    def setUp(self):
        self.client = APIClient()

        self.patient_data = {
            "first_name": "Youssef",
            "last_name": "Permission",
            "cin": "CRM-PERM-001",
            "phone": "22123499",
            "email": "crm.permission@example.com",
            "birth_date": "1994-05-12",
            "address": "Tunis",
            "medical_record_number": "MR-CRM-PERM-001",
            "diagnosis": "Permission test",
            "notes": "CRM permission test patient",
        }

    def test_accountant_cannot_create_patient(self):
        user = User.objects.create_user(
            username="accountant_crm_user",
            password="testpass123",
        )
        user.profile.role = "accountant"
        user.profile.save()

        self.client.force_authenticate(user=user)

        response = self.client.post("/api/crm/patients/", self.patient_data, format="json")

        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_secretary_can_create_patient(self):
        user = User.objects.create_user(
            username="secretary_crm_user",
            password="testpass123",
        )
        user.profile.role = "secretary"
        user.profile.save()

        self.client.force_authenticate(user=user)

        response = self.client.post("/api/crm/patients/", self.patient_data, format="json")

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)

class TicketComplaintApiTests(TestCase):
    def setUp(self):
        self.client = APIClient()

        self.user = User.objects.create_user(
            username="support_user",
            password="testpass123",
            first_name="Support",
            last_name="Agent",
        )
        self.user.profile.role = "support_client"
        self.user.profile.save()

        self.client.force_authenticate(user=self.user)

        self.patient = Patient.objects.create(
            first_name="Sofia",
            last_name="Martins",
            cin="CRM-TC-001",
            phone="22111111",
            email="sofia@example.com",
            medical_record_number="MR-TC-001",
        )

    def test_create_ticket_with_accented_values(self):
        response = self.client.post(
            "/api/crm/tickets/",
            {
                "titre": "Retard de réponse",
                "description": "Le patient demande un retour urgent.",
                "priorite": "Élevée",
                "statut": "Nouveau",
                "client": self.patient.id,
                "agents": [self.user.id],
            },
            format="json",
        )

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data["priorite"], "Élevée")
        self.assertEqual(response.data["agents"], [self.user.id])
        self.assertTrue(response.data["numero"].startswith("TCK-"))

    def test_update_ticket_status_with_accented_value(self):
        ticket = Ticket.objects.create(
            titre="Question facture",
            description="Demande de clarification.",
            priorite="Moyenne",
            statut="Nouveau",
            client=self.patient,
        )

        response = self.client.patch(
            f"/api/crm/tickets/{ticket.id}/",
            {"statut": "Résolu"},
            format="json",
        )

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["statut"], "Résolu")

    def test_create_complaint(self):
        response = self.client.post(
            "/api/crm/complaints/",
            {
                "description": "Réclamation concernant la facturation.",
                "statut": "Nouvelle",
                "client": self.patient.id,
            },
            format="json",
        )

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data["client_name"], "Sofia Martins")

    def test_update_complaint_status_with_accented_value(self):
        complaint = Complaint.objects.create(
            description="Retard dans la prise en charge.",
            statut="Nouvelle",
            client=self.patient,
        )

        response = self.client.patch(
            f"/api/crm/complaints/{complaint.id}/",
            {"statut": "Résolue"},
            format="json",
        )

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["statut"], "Résolue")
        
class MissedSessionAutoTicketTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(username="doc", password="pass")
        self.patient = Patient.objects.create(
            first_name="Youssef",
            last_name="Triki",
            cin="11223344",
            phone="22000001",
            email="youssef@example.com",
            birth_date="1980-03-15",
            address="Sfax",
            medical_record_number="MR-9001",
            diagnosis="Test",
        )
        self.plan = TreatmentPlan.objects.create(
            patient=self.patient,
            name="Plan Test",
            total_sessions=10,
            dose_per_session="2.00",
            total_dose="20.00",
            status="active",
        )
        self.machine = Machine.objects.create(name="LINAC-T", status="active")
        self.room = Room.objects.create(name="Salle T", status="active")

    def test_missed_session_creates_ticket(self):
        """Marking a session as missed must auto-create a follow-up ticket."""
        session = TreatmentSession.objects.create(
            patient=self.patient,
            treatment_plan=self.plan,
            session_number=3,
            scheduled_datetime="2026-08-05T10:00:00Z",
            status="scheduled",
            machine=self.machine,
            room=self.room,
        )

        # No ticket yet
        self.assertEqual(Ticket.objects.filter(client=self.patient).count(), 0)

        # Mark as missed
        session.status = "missed"
        session.save()

        tickets = Ticket.objects.filter(client=self.patient)
        self.assertEqual(tickets.count(), 1)
        ticket = tickets.first()
        self.assertIn("Séance manquée", ticket.titre)
        self.assertEqual(ticket.priorite, "Élevée")
        self.assertEqual(ticket.statut, "Nouveau")

    def test_missed_session_ticket_is_idempotent(self):
        """Saving a missed session twice must not create duplicate tickets."""
        session = TreatmentSession.objects.create(
            patient=self.patient,
            treatment_plan=self.plan,
            session_number=4,
            scheduled_datetime="2026-08-06T10:00:00Z",
            status="scheduled",
            machine=self.machine,
            room=self.room,
        )

        session.status = "missed"
        session.save()
        session.save()  # second save — should not duplicate

        self.assertEqual(Ticket.objects.filter(client=self.patient).count(), 1)

    def test_completed_session_does_not_create_ticket(self):
        """A completed session must not trigger a ticket."""
        session = TreatmentSession.objects.create(
            patient=self.patient,
            treatment_plan=self.plan,
            session_number=5,
            scheduled_datetime="2026-08-07T10:00:00Z",
            status="scheduled",
            machine=self.machine,
            room=self.room,
        )

        session.status = "completed"
        session.save()

        self.assertEqual(Ticket.objects.filter(client=self.patient).count(), 0)