# Generated by Django 6.0.6 on 2026-07-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlogentry',
            new_name='audit_audit_content_82c7f9_idx',
            old_name='audit_audit_content_5c1e4a_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogentry',
            new_name='audit_audit_created_3e5798_idx',
            old_name='audit_audit_created_9b2f7d_idx',
        ),
    ]
