# Generated by Django 6.0.6 on 2026-08-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicalproduct',
            new_name='stocks_medi_categor_56d0b5_idx',
            old_name='stocks_medi_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='stockentry',
            new_name='stocks_stoc_product_d771d8_idx',
            old_name='stocks_stoc_product_exp_idx',
        ),
    ]
