# Generated by Django 6.0.6 on 2026-07-15 22:50

from django.db import migrations, models


def normalize_old_casing(apps, schema_editor):
    """
    Rows written before this fix could have role='Manager' or role='Assistant'
    (the old, reversed-casing values). Normalize them to the corrected slugs
    so existing users don't silently fail every role-based permission check.
    """
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserProfile.objects.filter(role="Manager").update(role="manager")
    UserProfile.objects.filter(role="Assistant").update(role="assistant")


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('radiotherapist', 'Radiotherapist'), ('secretary', 'Secretary'), ('accountant', 'Accountant'), ('hr', 'HR'), ('support_client', 'Support Client'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('assistant', 'Assistant')], default='secretary', max_length=30),
        ),
        migrations.RunPython(normalize_old_casing, reverse_noop),
    ]