# Generated by Django 6.0.6 on 2026-08-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Super Administrateur (accès total au système)'),
        ),
    ]
