# Generated by Django 4.2.30 on 2026-08-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='view_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
