# Generated by Django 4.2.30 on 2026-08-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rolepermission_view_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('secretary', 'Secretary'), ('accountant', 'Accountant'), ('hr', 'HR'), ('support_client', 'Support Client'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('assistant', 'Assistant')], default='secretary', max_length=30),
        ),
    ]
