# Generated by Django 6.0.6 on 2026-07-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('diagnosis', models.TextField(blank=True)),
                ('protocol', models.TextField(blank=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('dose_per_session', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_dose', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='crm.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
