# Generated by Django 6.0.6 on 2026-07-15 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_treatmentsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('Faible', 'Faible'), ('Moyenne', 'Moyenne'), ('Élevée', 'Élevée'), ('Critique', 'Critique')], default='Faible', max_length=20)),
                ('statut', models.CharField(choices=[('Nouveau', 'Nouveau'), ('En cours', 'En cours'), ('En attente', 'En attente'), ('Résolu', 'Résolu'), ('Fermé', 'Fermé')], default='Nouveau', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agents', models.ManyToManyField(blank=True, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='crm.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]