# Generated by Django 6.0.6 on 2026-07-15 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('Nouvelle', 'Nouvelle'), ('En traitement', 'En traitement'), ('Résolue', 'Résolue'), ('Fermée', 'Fermée')], default='Nouvelle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='crm.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
    