# Generated by Django 6.0.6 on 2026-08-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_ticket_sla'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='ticket_sla_idx',
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
