# Generated by Django 6.0.6 on 2026-08-11 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_trt05_protocols'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='calibration_interval_days',
            field=models.PositiveIntegerField(default=365, help_text='Intervalle de calibration en jours'),
        ),
        migrations.AddField(
            model_name='machine',
            name='last_calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='location',
            field=models.CharField(blank=True, help_text='Room / building', max_length=150),
        ),
        migrations.AddField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='machine',
            name='mtbf_hours',
            field=models.FloatField(default=0, help_text='Mean Time Between Failures (heures)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='mttr_hours',
            field=models.FloatField(default=0, help_text='Mean Time To Repair (heures)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='next_calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Coût d'acquisition en TND", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='residual_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur résiduelle TND', max_digits=12),
        ),
        migrations.AddField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='machine',
            name='useful_life_years',
            field=models.PositiveSmallIntegerField(default=10, help_text="Durée d'amortissement en années"),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('calibration', 'Calibration'), ('inspection', 'Inspection')], default='preventive', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('technician', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, choices=[('ok', 'OK — Opérationnel'), ('repaired', 'Réparé'), ('partial', 'Partiellement résolu'), ('failed', 'Échec / Renvoi fournisseur')], max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text="Coût de l'intervention TND", max_digits=10, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='crm.machine')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
