# Generated by Django 6.0.6 on 2026-08-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
