# Generated by Django 4.2.30 on 2026-08-27 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0017_remove_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=1, help_text="Nombre maximum d'occupants (patient + accompagnants)"),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('treatment', 'Traitement'), ('recovery', 'Rétablissement'), ('imaging', 'Imagerie'), ('operating', 'Bloc opératoire'), ('waiting', "Salle d'attente"), ('office', 'Bureau')], default='consultation', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, help_text='Bâtiment / étage / aile', max_length=150),
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupants', models.PositiveSmallIntegerField(default=1, help_text="Nombre total d'occupants (patient + accompagnants)")),
                ('notes_companions', models.CharField(blank=True, help_text='Ex : épouse + infirmière, mère', max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmée'), ('pending', 'En attente'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='confirmed', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='crm.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='crm.room')),
            ],
            options={
                'verbose_name': 'Réservation de salle',
                'verbose_name_plural': 'Réservations de salles',
                'ordering': ['start_datetime'],
            },
        ),
    ]
