# Generated by Django 4.2.30 on 2026-08-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_room_usage_machine_room_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=1, help_text="Nombre maximum d'occupants (patient + accompagnants). Ignoré pour Stock."),
        ),
    ]
