# Generated by Django 4.2.30 on 2026-08-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Salle dédiée à ce créneau (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_availabilities', to='crm.room'),
        ),
    ]
