# Generated by Django 4.2.30 on 2026-08-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_doctoravailability_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentextension',
            name='appointment_type',
            field=models.CharField(choices=[('simple', 'Consultation simple (15 min)'), ('complex', 'Consultation complexe (30 min)'), ('followup', 'Suivi de traitement (45 min)'), ('urgency', 'Urgence'), ('operation', 'Opération chirurgicale')], default='simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='usage',
            field=models.CharField(choices=[('medicalized', 'Chambre médicalisée'), ('patient_appointment', 'Salle de rendez-vous'), ('operation_room', "Salle d'opération"), ('stock', 'Stock / Local technique')], default='patient_appointment', help_text='medicalized = chambre post-op/nuit ; patient_appointment = consultation/radio/ophtalmo ; operation_room = bloc opératoire ; stock = local matériel', max_length=30),
        ),
    ]
