# Generated by Django 4.2.30 on 2026-08-29 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_appointmentextension_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentextension',
            name='appointment_type',
            field=models.CharField(choices=[('simple', 'Consultation simple (15 min)'), ('complex', 'Consultation complexe (30 min)'), ('followup', 'Suivi de traitement (45 min)'), ('urgency', 'Urgence')], default='simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='operationbooking',
            name='donor_patient',
            field=models.ForeignKey(blank=True, help_text='Patient donneur (organe, sang, moelle, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_bookings_as_donor', to='crm.patient'),
        ),
        migrations.AlterField(
            model_name='operationbooking',
            name='operation_type',
            field=models.CharField(blank=True, help_text='Ex : Cholécystectomie, Greffe rénale, Appendicectomie', max_length=200),
        ),
        migrations.AlterField(
            model_name='operationbooking',
            name='room',
            field=models.ForeignKey(help_text="Doit être une salle d'opération (usage=operation_room).", on_delete=django.db.models.deletion.CASCADE, related_name='operation_bookings', to='crm.room'),
        ),
        migrations.AlterField(
            model_name='operationbooking',
            name='with_donor',
            field=models.BooleanField(default=False, help_text="Cocher si l'opération implique un donneur."),
        ),
        migrations.AlterField(
            model_name='operationstaff',
            name='role',
            field=models.CharField(help_text="Rôle dans l'opération : Chirurgien principal, Anesthésiste, Infirmier(e) de bloc…", max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='usage',
            field=models.CharField(choices=[('medicalized', 'Chambre médicalisée'), ('patient_appointment', 'Salle de rendez-vous'), ('operation_room', "Salle d'opération"), ('stock', 'Stock / Local technique')], default='patient_appointment', help_text='medicalized = chambre post-op/nuit ; patient_appointment = consultation/radio/ophtalmo ; stock = local matériel', max_length=30),
        ),
    ]
