/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TeamScheduleRouteImport } from './routes/team-schedule'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as SocialEventsRouteImport } from './routes/social-events'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SalaryAdvancesRouteImport } from './routes/salary-advances'
import { Route as Roles_permissionRouteImport } from './routes/roles_permission'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as RecouvrementRouteImport } from './routes/recouvrement'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DocumentRequestsRouteImport } from './routes/document-requests'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as CnamRouteImport } from './routes/cnam'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AbsencesRouteImport } from './routes/absences'
import { Route as AbonnementsRouteImport } from './routes/abonnements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as PatientsNewRouteImport } from './routes/patients.new'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as PatientLoginRouteImport } from './routes/patient.login'
import { Route as PatientLayoutRouteImport } from './routes/patient.layout'
import { Route as PatientPortalRatingRouteImport } from './routes/patient-portal/rating'
import { Route as PatientPortalProfileRouteImport } from './routes/patient-portal/profile'
import { Route as PatientPortalMessagesRouteImport } from './routes/patient-portal/messages'
import { Route as PatientPortalMedicalHistoryRouteImport } from './routes/patient-portal/medical-history'
import { Route as PatientPortalDocumentsRouteImport } from './routes/patient-portal/documents'
import { Route as PatientPortalDashboardRouteImport } from './routes/patient-portal/dashboard'
import { Route as PatientPortalAppointmentsRouteImport } from './routes/patient-portal/appointments'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamScheduleRoute = TeamScheduleRouteImport.update({
  id: '/team-schedule',
  path: '/team-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialEventsRoute = SocialEventsRouteImport.update({
  id: '/social-events',
  path: '/social-events',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryAdvancesRoute = SalaryAdvancesRouteImport.update({
  id: '/salary-advances',
  path: '/salary-advances',
  getParentRoute: () => rootRouteImport,
} as any)
const Roles_permissionRoute = Roles_permissionRouteImport.update({
  id: '/roles_permission',
  path: '/roles_permission',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const RecouvrementRoute = RecouvrementRouteImport.update({
  id: '/recouvrement',
  path: '/recouvrement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentRequestsRoute = DocumentRequestsRouteImport.update({
  id: '/document-requests',
  path: '/document-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CnamRoute = CnamRouteImport.update({
  id: '/cnam',
  path: '/cnam',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsencesRoute = AbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementsRoute = AbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientLoginRoute = PatientLoginRouteImport.update({
  id: '/patient/login',
  path: '/patient/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientLayoutRoute = PatientLayoutRouteImport.update({
  id: '/patient/layout',
  path: '/patient/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalRatingRoute = PatientPortalRatingRouteImport.update({
  id: '/patient-portal/rating',
  path: '/patient-portal/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalProfileRoute = PatientPortalProfileRouteImport.update({
  id: '/patient-portal/profile',
  path: '/patient-portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalMessagesRoute = PatientPortalMessagesRouteImport.update({
  id: '/patient-portal/messages',
  path: '/patient-portal/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalMedicalHistoryRoute =
  PatientPortalMedicalHistoryRouteImport.update({
    id: '/patient-portal/medical-history',
    path: '/patient-portal/medical-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientPortalDocumentsRoute = PatientPortalDocumentsRouteImport.update({
  id: '/patient-portal/documents',
  path: '/patient-portal/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalDashboardRoute = PatientPortalDashboardRouteImport.update({
  id: '/patient-portal/dashboard',
  path: '/patient-portal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalAppointmentsRoute =
  PatientPortalAppointmentsRouteImport.update({
    id: '/patient-portal/appointments',
    path: '/patient-portal/appointments',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/absences': typeof AbsencesRoute
  '/accounting': typeof AccountingRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/cnam': typeof CnamRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/document-requests': typeof DocumentRequestsRoute
  '/employees': typeof EmployeesRoute
  '/equipment': typeof EquipmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formations': typeof FormationsRoute
  '/historique': typeof HistoriqueRoute
  '/incidents': typeof IncidentsRoute
  '/leaves': typeof LeavesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/portal': typeof PortalRoute
  '/protocols': typeof ProtocolsRoute
  '/recouvrement': typeof RecouvrementRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles_permission': typeof Roles_permissionRoute
  '/salary-advances': typeof SalaryAdvancesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/social-events': typeof SocialEventsRoute
  '/stocks': typeof StocksRoute
  '/team-schedule': typeof TeamScheduleRoute
  '/tickets': typeof TicketsRoute
  '/treatments': typeof TreatmentsRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/patient-portal/appointments': typeof PatientPortalAppointmentsRoute
  '/patient-portal/dashboard': typeof PatientPortalDashboardRoute
  '/patient-portal/documents': typeof PatientPortalDocumentsRoute
  '/patient-portal/medical-history': typeof PatientPortalMedicalHistoryRoute
  '/patient-portal/messages': typeof PatientPortalMessagesRoute
  '/patient-portal/profile': typeof PatientPortalProfileRoute
  '/patient-portal/rating': typeof PatientPortalRatingRoute
  '/patient/layout': typeof PatientLayoutRoute
  '/patient/login': typeof PatientLoginRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/absences': typeof AbsencesRoute
  '/accounting': typeof AccountingRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/cnam': typeof CnamRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/document-requests': typeof DocumentRequestsRoute
  '/employees': typeof EmployeesRoute
  '/equipment': typeof EquipmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formations': typeof FormationsRoute
  '/historique': typeof HistoriqueRoute
  '/incidents': typeof IncidentsRoute
  '/leaves': typeof LeavesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/portal': typeof PortalRoute
  '/protocols': typeof ProtocolsRoute
  '/recouvrement': typeof RecouvrementRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles_permission': typeof Roles_permissionRoute
  '/salary-advances': typeof SalaryAdvancesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/social-events': typeof SocialEventsRoute
  '/stocks': typeof StocksRoute
  '/team-schedule': typeof TeamScheduleRoute
  '/tickets': typeof TicketsRoute
  '/treatments': typeof TreatmentsRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/patient-portal/appointments': typeof PatientPortalAppointmentsRoute
  '/patient-portal/dashboard': typeof PatientPortalDashboardRoute
  '/patient-portal/documents': typeof PatientPortalDocumentsRoute
  '/patient-portal/medical-history': typeof PatientPortalMedicalHistoryRoute
  '/patient-portal/messages': typeof PatientPortalMessagesRoute
  '/patient-portal/profile': typeof PatientPortalProfileRoute
  '/patient-portal/rating': typeof PatientPortalRatingRoute
  '/patient/layout': typeof PatientLayoutRoute
  '/patient/login': typeof PatientLoginRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/invoices': typeof InvoicesIndexRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/absences': typeof AbsencesRoute
  '/accounting': typeof AccountingRoute
  '/analytics': typeof AnalyticsRoute
  '/board': typeof BoardRoute
  '/calendar': typeof CalendarRoute
  '/cnam': typeof CnamRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/document-requests': typeof DocumentRequestsRoute
  '/employees': typeof EmployeesRoute
  '/equipment': typeof EquipmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/formations': typeof FormationsRoute
  '/historique': typeof HistoriqueRoute
  '/incidents': typeof IncidentsRoute
  '/leaves': typeof LeavesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/portal': typeof PortalRoute
  '/protocols': typeof ProtocolsRoute
  '/recouvrement': typeof RecouvrementRoute
  '/recruitment': typeof RecruitmentRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles_permission': typeof Roles_permissionRoute
  '/salary-advances': typeof SalaryAdvancesRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/social-events': typeof SocialEventsRoute
  '/stocks': typeof StocksRoute
  '/team-schedule': typeof TeamScheduleRoute
  '/tickets': typeof TicketsRoute
  '/treatments': typeof TreatmentsRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/patient-portal/appointments': typeof PatientPortalAppointmentsRoute
  '/patient-portal/dashboard': typeof PatientPortalDashboardRoute
  '/patient-portal/documents': typeof PatientPortalDocumentsRoute
  '/patient-portal/medical-history': typeof PatientPortalMedicalHistoryRoute
  '/patient-portal/messages': typeof PatientPortalMessagesRoute
  '/patient-portal/profile': typeof PatientPortalProfileRoute
  '/patient-portal/rating': typeof PatientPortalRatingRoute
  '/patient/layout': typeof PatientLayoutRoute
  '/patient/login': typeof PatientLoginRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnements'
    | '/absences'
    | '/accounting'
    | '/analytics'
    | '/board'
    | '/calendar'
    | '/cnam'
    | '/complaints'
    | '/dashboard'
    | '/document-requests'
    | '/employees'
    | '/equipment'
    | '/forgot-password'
    | '/formations'
    | '/historique'
    | '/incidents'
    | '/leaves'
    | '/messages'
    | '/notifications'
    | '/payments'
    | '/payroll'
    | '/portal'
    | '/protocols'
    | '/recouvrement'
    | '/recruitment'
    | '/reports'
    | '/reset-password'
    | '/roles_permission'
    | '/salary-advances'
    | '/schedule'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/social-events'
    | '/stocks'
    | '/team-schedule'
    | '/tickets'
    | '/treatments'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/patient-portal/appointments'
    | '/patient-portal/dashboard'
    | '/patient-portal/documents'
    | '/patient-portal/medical-history'
    | '/patient-portal/messages'
    | '/patient-portal/profile'
    | '/patient-portal/rating'
    | '/patient/layout'
    | '/patient/login'
    | '/patients/$patientId'
    | '/patients/new'
    | '/invoices/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnements'
    | '/absences'
    | '/accounting'
    | '/analytics'
    | '/board'
    | '/calendar'
    | '/cnam'
    | '/complaints'
    | '/dashboard'
    | '/document-requests'
    | '/employees'
    | '/equipment'
    | '/forgot-password'
    | '/formations'
    | '/historique'
    | '/incidents'
    | '/leaves'
    | '/messages'
    | '/notifications'
    | '/payments'
    | '/payroll'
    | '/portal'
    | '/protocols'
    | '/recouvrement'
    | '/recruitment'
    | '/reports'
    | '/reset-password'
    | '/roles_permission'
    | '/salary-advances'
    | '/schedule'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/social-events'
    | '/stocks'
    | '/team-schedule'
    | '/tickets'
    | '/treatments'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/patient-portal/appointments'
    | '/patient-portal/dashboard'
    | '/patient-portal/documents'
    | '/patient-portal/medical-history'
    | '/patient-portal/messages'
    | '/patient-portal/profile'
    | '/patient-portal/rating'
    | '/patient/layout'
    | '/patient/login'
    | '/patients/$patientId'
    | '/patients/new'
    | '/invoices'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/abonnements'
    | '/absences'
    | '/accounting'
    | '/analytics'
    | '/board'
    | '/calendar'
    | '/cnam'
    | '/complaints'
    | '/dashboard'
    | '/document-requests'
    | '/employees'
    | '/equipment'
    | '/forgot-password'
    | '/formations'
    | '/historique'
    | '/incidents'
    | '/leaves'
    | '/messages'
    | '/notifications'
    | '/payments'
    | '/payroll'
    | '/portal'
    | '/protocols'
    | '/recouvrement'
    | '/recruitment'
    | '/reports'
    | '/reset-password'
    | '/roles_permission'
    | '/salary-advances'
    | '/schedule'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/social-events'
    | '/stocks'
    | '/team-schedule'
    | '/tickets'
    | '/treatments'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/patient-portal/appointments'
    | '/patient-portal/dashboard'
    | '/patient-portal/documents'
    | '/patient-portal/medical-history'
    | '/patient-portal/messages'
    | '/patient-portal/profile'
    | '/patient-portal/rating'
    | '/patient/layout'
    | '/patient/login'
    | '/patients/$patientId'
    | '/patients/new'
    | '/invoices/'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementsRoute: typeof AbonnementsRoute
  AbsencesRoute: typeof AbsencesRoute
  AccountingRoute: typeof AccountingRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BoardRoute: typeof BoardRoute
  CalendarRoute: typeof CalendarRoute
  CnamRoute: typeof CnamRoute
  ComplaintsRoute: typeof ComplaintsRoute
  DashboardRoute: typeof DashboardRoute
  DocumentRequestsRoute: typeof DocumentRequestsRoute
  EmployeesRoute: typeof EmployeesRoute
  EquipmentRoute: typeof EquipmentRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FormationsRoute: typeof FormationsRoute
  HistoriqueRoute: typeof HistoriqueRoute
  IncidentsRoute: typeof IncidentsRoute
  LeavesRoute: typeof LeavesRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  PayrollRoute: typeof PayrollRoute
  PortalRoute: typeof PortalRoute
  ProtocolsRoute: typeof ProtocolsRoute
  RecouvrementRoute: typeof RecouvrementRoute
  RecruitmentRoute: typeof RecruitmentRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Roles_permissionRoute: typeof Roles_permissionRoute
  SalaryAdvancesRoute: typeof SalaryAdvancesRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SocialEventsRoute: typeof SocialEventsRoute
  StocksRoute: typeof StocksRoute
  TeamScheduleRoute: typeof TeamScheduleRoute
  TicketsRoute: typeof TicketsRoute
  TreatmentsRoute: typeof TreatmentsRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  PatientPortalAppointmentsRoute: typeof PatientPortalAppointmentsRoute
  PatientPortalDashboardRoute: typeof PatientPortalDashboardRoute
  PatientPortalDocumentsRoute: typeof PatientPortalDocumentsRoute
  PatientPortalMedicalHistoryRoute: typeof PatientPortalMedicalHistoryRoute
  PatientPortalMessagesRoute: typeof PatientPortalMessagesRoute
  PatientPortalProfileRoute: typeof PatientPortalProfileRoute
  PatientPortalRatingRoute: typeof PatientPortalRatingRoute
  PatientLayoutRoute: typeof PatientLayoutRoute
  PatientLoginRoute: typeof PatientLoginRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-schedule': {
      id: '/team-schedule'
      path: '/team-schedule'
      fullPath: '/team-schedule'
      preLoaderRoute: typeof TeamScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-events': {
      id: '/social-events'
      path: '/social-events'
      fullPath: '/social-events'
      preLoaderRoute: typeof SocialEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-advances': {
      id: '/salary-advances'
      path: '/salary-advances'
      fullPath: '/salary-advances'
      preLoaderRoute: typeof SalaryAdvancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles_permission': {
      id: '/roles_permission'
      path: '/roles_permission'
      fullPath: '/roles_permission'
      preLoaderRoute: typeof Roles_permissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recouvrement': {
      id: '/recouvrement'
      path: '/recouvrement'
      fullPath: '/recouvrement'
      preLoaderRoute: typeof RecouvrementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-requests': {
      id: '/document-requests'
      path: '/document-requests'
      fullPath: '/document-requests'
      preLoaderRoute: typeof DocumentRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cnam': {
      id: '/cnam'
      path: '/cnam'
      fullPath: '/cnam'
      preLoaderRoute: typeof CnamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absences': {
      id: '/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AbsencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnements': {
      id: '/abonnements'
      path: '/abonnements'
      fullPath: '/abonnements'
      preLoaderRoute: typeof AbonnementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/login': {
      id: '/patient/login'
      path: '/patient/login'
      fullPath: '/patient/login'
      preLoaderRoute: typeof PatientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/layout': {
      id: '/patient/layout'
      path: '/patient/layout'
      fullPath: '/patient/layout'
      preLoaderRoute: typeof PatientLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/rating': {
      id: '/patient-portal/rating'
      path: '/patient-portal/rating'
      fullPath: '/patient-portal/rating'
      preLoaderRoute: typeof PatientPortalRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/profile': {
      id: '/patient-portal/profile'
      path: '/patient-portal/profile'
      fullPath: '/patient-portal/profile'
      preLoaderRoute: typeof PatientPortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/messages': {
      id: '/patient-portal/messages'
      path: '/patient-portal/messages'
      fullPath: '/patient-portal/messages'
      preLoaderRoute: typeof PatientPortalMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/medical-history': {
      id: '/patient-portal/medical-history'
      path: '/patient-portal/medical-history'
      fullPath: '/patient-portal/medical-history'
      preLoaderRoute: typeof PatientPortalMedicalHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/documents': {
      id: '/patient-portal/documents'
      path: '/patient-portal/documents'
      fullPath: '/patient-portal/documents'
      preLoaderRoute: typeof PatientPortalDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/dashboard': {
      id: '/patient-portal/dashboard'
      path: '/patient-portal/dashboard'
      fullPath: '/patient-portal/dashboard'
      preLoaderRoute: typeof PatientPortalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal/appointments': {
      id: '/patient-portal/appointments'
      path: '/patient-portal/appointments'
      fullPath: '/patient-portal/appointments'
      preLoaderRoute: typeof PatientPortalAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementsRoute: AbonnementsRoute,
  AbsencesRoute: AbsencesRoute,
  AccountingRoute: AccountingRoute,
  AnalyticsRoute: AnalyticsRoute,
  BoardRoute: BoardRoute,
  CalendarRoute: CalendarRoute,
  CnamRoute: CnamRoute,
  ComplaintsRoute: ComplaintsRoute,
  DashboardRoute: DashboardRoute,
  DocumentRequestsRoute: DocumentRequestsRoute,
  EmployeesRoute: EmployeesRoute,
  EquipmentRoute: EquipmentRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FormationsRoute: FormationsRoute,
  HistoriqueRoute: HistoriqueRoute,
  IncidentsRoute: IncidentsRoute,
  LeavesRoute: LeavesRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  PayrollRoute: PayrollRoute,
  PortalRoute: PortalRoute,
  ProtocolsRoute: ProtocolsRoute,
  RecouvrementRoute: RecouvrementRoute,
  RecruitmentRoute: RecruitmentRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Roles_permissionRoute: Roles_permissionRoute,
  SalaryAdvancesRoute: SalaryAdvancesRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SocialEventsRoute: SocialEventsRoute,
  StocksRoute: StocksRoute,
  TeamScheduleRoute: TeamScheduleRoute,
  TicketsRoute: TicketsRoute,
  TreatmentsRoute: TreatmentsRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  PatientPortalAppointmentsRoute: PatientPortalAppointmentsRoute,
  PatientPortalDashboardRoute: PatientPortalDashboardRoute,
  PatientPortalDocumentsRoute: PatientPortalDocumentsRoute,
  PatientPortalMedicalHistoryRoute: PatientPortalMedicalHistoryRoute,
  PatientPortalMessagesRoute: PatientPortalMessagesRoute,
  PatientPortalProfileRoute: PatientPortalProfileRoute,
  PatientPortalRatingRoute: PatientPortalRatingRoute,
  PatientLayoutRoute: PatientLayoutRoute,
  PatientLoginRoute: PatientLoginRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
