import { apiFetch } from "./api";

// ── Types ────────────────────────────────────────────────────────────────────

export type ApiPatient = {
  id: number;
  first_name: string;
  last_name: string;
  cin: string | null;
  phone: string;
  email: string;
  birth_date: string | null;
  address: string;
  // Always returned by the backend — auto-generated as MRN-YYYY-NNNN.
  // Read-only: never send this on POST/PATCH.
  medical_record_number: string;
  diagnosis: string;
  notes: string;
  created_at: string;
  updated_at: string;
};

export type ApiTreatmentPlan = {
  id: number;
  patient: number;
  patient_name: string;
  name: string;
  diagnosis: string;
  protocol: string;
  total_sessions: number;
  dose_per_session: number;
  total_dose: number;
  start_date: string | null;
  end_date: string | null;
  status: "draft" | "active" | "completed" | "cancelled";
  notes: string;
  // Live computed fields from the backend
  cumulative_dose: number;
  sessions_completed: number;
  dose_percentage: number;
  created_at: string;
  updated_at: string;
};

export type ApiAppointment = {
  id: number;
  patient: number;
  patient_name: string;
  title: string;
  appointment_date: string;
  status: "scheduled" | "confirmed" | "cancelled" | "done";
  reason: string;
  notes: string;
  created_at: string;
};

export type ApiTicketSummary = {
  id: number;
  numero: string;
  titre: string;
  statut: string;
  priorite: string;
  created_at: string;
  updated_at: string;
};

export type ApiFinanceSummary = {
  total_invoiced: number;
  total_paid: number;
  balance_due: number;
  open_invoices_count: number;
};

export type ApiPatient360 = {
  patient: ApiPatient;
  active_plan: ApiTreatmentPlan | null;
  upcoming_appointments: ApiAppointment[];
  open_tickets: ApiTicketSummary[];
  finance_summary: ApiFinanceSummary;
};

type Paginated<T> = { results: T[]; count: number } | T[];

function unwrap<T>(data: Paginated<T>): T[] {
  return Array.isArray(data) ? data : data.results;
}

// ── Patient CRUD ─────────────────────────────────────────────────────────────

export async function fetchPatients(params?: {
  search?: string;
  ordering?: string;
  page?: number;
}): Promise<{ results: ApiPatient[]; count: number }> {
  const qs = new URLSearchParams();
  if (params?.search) qs.set("search", params.search);
  if (params?.ordering) qs.set("ordering", params.ordering);
  if (params?.page) qs.set("page", String(params.page));
  const query = qs.toString() ? `?${qs}` : "";
  const data = await apiFetch<Paginated<ApiPatient>>(`/crm/patients/${query}`);
  if (Array.isArray(data)) return { results: data, count: data.length };
  return data as { results: ApiPatient[]; count: number };
}

/**
 * Flat array version of fetchPatients — for pages that just need the list
 * (dashboard, calendar, dropdowns) without pagination metadata.
 * Always fetches page_size=200 to get all patients in one call.
 */
export async function fetchAllPatients(): Promise<ApiPatient[]> {
  const data = await apiFetch<Paginated<ApiPatient>>("/crm/patients/?page_size=200");
  return Array.isArray(data) ? data : data.results;
}

export async function fetchPatient(id: number): Promise<ApiPatient> {
  return apiFetch<ApiPatient>(`/crm/patients/${id}/`);
}

/** Full 360° dossier — patient + active plan + appointments + tickets + finance. */
export async function fetchPatient360(id: number): Promise<ApiPatient360> {
  return apiFetch<ApiPatient360>(`/crm/patients/${id}/360/`);
}

// MRN is auto-generated by the backend — never include it in the write payload.
export type PatientWritePayload = {
  first_name: string;
  last_name: string;
  cin?: string | null;
  phone?: string;
  email?: string;
  birth_date?: string | null;
  address?: string;
  diagnosis?: string;
  notes?: string;
};

export function createPatient(payload: PatientWritePayload): Promise<ApiPatient> {
  return apiFetch<ApiPatient>("/crm/patients/", {
    method: "POST",
    body: payload,
  });
}

export function updatePatient(
  id: number,
  payload: Partial<PatientWritePayload>,
): Promise<ApiPatient> {
  return apiFetch<ApiPatient>(`/crm/patients/${id}/`, {
    method: "PATCH",
    body: payload,
  });
}

export function deletePatient(id: number): Promise<void> {
  return apiFetch<void>(`/crm/patients/${id}/`, { method: "DELETE" });
}

// ── Treatment Plans ──────────────────────────────────────────────────────────

export async function fetchTreatmentPlans(patientId?: number): Promise<ApiTreatmentPlan[]> {
  const qs = patientId ? `?patient=${patientId}` : "";
  const data = await apiFetch<Paginated<ApiTreatmentPlan>>(`/crm/treatment-plans/${qs}`);
  return unwrap(data);
}

export async function fetchTreatmentPlan(id: number): Promise<ApiTreatmentPlan> {
  return apiFetch<ApiTreatmentPlan>(`/crm/treatment-plans/${id}/`);
}

export type TreatmentPlanWritePayload = {
  patient: number;
  name: string;
  diagnosis?: string;
  protocol?: string;
  total_sessions: number;
  dose_per_session: number;
  total_dose: number;
  start_date?: string | null;
  end_date?: string | null;
  status?: "draft" | "active" | "completed" | "cancelled";
  notes?: string;
};

export function createTreatmentPlan(payload: TreatmentPlanWritePayload): Promise<ApiTreatmentPlan> {
  return apiFetch<ApiTreatmentPlan>("/crm/treatment-plans/", {
    method: "POST",
    body: payload,
  });
}

export function updateTreatmentPlan(
  id: number,
  payload: Partial<TreatmentPlanWritePayload>,
): Promise<ApiTreatmentPlan> {
  return apiFetch<ApiTreatmentPlan>(`/crm/treatment-plans/${id}/`, {
    method: "PATCH",
    body: payload,
  });
}